[package]
name = "fuse_mt"
version = "0.2.2"
authors = ["William R. Fraser <wfraser@codewise.org>"]
repository = "https://github.com/wfraser/fuse-mt"
description = "(work in progress) A higher-level FUSE filesystem library with multi-threading and inode->path translation."
keywords = ["fuse", "filesystem"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
fuse = { git = "https://github.com/nivekuil/rust-fuse" }
libc = "0.2"
log = "0.3"
threadpool = "1.0"
time = "0.1"
